In [11]:
import pandas as pd

df=pd.read_csv("iris_dataset.csv")

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
x= df.iloc[:, :4].values
#label
y = df["target"].values

In [17]:
ptest = x[149]
ytest = y[149]

ptrain = x[:149]
ytrain = y[:149]

ytest , ptest, ptrain

(2,
 array([5.9, 3. , 5.1, 1.8]),
 array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
      

In [ ]:
import numpy as np

def euclidean_distance(p1, p2):
    return np.sqrt(np.sum((p1 - p2)**2))

distances = []

for i in range(len(ptrain)):
    d = euclidean_distance(ptest, ptrain[i])
    distances.append((float(d), int(ytrain[i])))

def cldistance(item):
    return item[0]
distances = sorted(distances , key= cldistance)    

In [36]:
k = 3
nghbrk3 = distances[:k]
classes = [n[1] for n in nghbrk3]
#n[1] = classes in tuple

predk3 = max(set(classes), key= classes.count)  

ytest, distances[:3] , predk3

(2,
 [(0.282842712474618, 2), (0.31622776601683766, 2), (0.33166247903553997, 2)],
 2)

In [34]:
mean = ptrain.mean(axis=0)
std = ptrain.std(axis=0)
ptrain_norm = (ptrain- mean)/std
ptest_norm = (ptest- mean)/ std
ptest_norm.round(4)

array([ 0.0689, -0.1324,  0.7668,  0.795 ])

In [39]:
distances_norm = []

for i in range(len(ptrain_norm)):
    d = euclidean_distance(ptest_norm, ptrain_norm[i])
    distances_norm.append((d, ytrain[i]))

  
def cldistance_norm(item):
    return item[0]
distances_norm = sorted(distances_norm , key= cldistance_norm)  

In [40]:
k = 3
nghbrk3 = distances_norm[:k]
classes = [n[1] for n in nghbrk3]
#n[1] = classes in tuple

predk3_norm = max(set(classes), key= classes.count)  

distances_norm[:3], predk3_norm, predk3, ytest

([(0.20875357970565467, 2), (0.26687654224764196, 2), (0.4894563929663544, 1)],
 2,
 2,
 2)

نرمال‌سازی به روش Z-Score

مزیت‌ها:

همهٔ ویژگی‌ها در یک مقیاس قرار می‌گیرند

میانگین = 0 ، انحراف معیار = ۱

هیچ ویژگی غالب نمی‌شود

فاصله‌ها منصفانه محاسبه می‌شوند

۳. مقایسه عملکرد قبل و بعد از نرمال‌سازی

نتیجه معمولاً این است:

مدل غیرنرمال‌شده دقت کمتر

مدل نرمال‌شده دقت بیشتر و تصمیم‌گیری پایدارتر

علت:

بدون نرمال‌سازی، ویژگی‌های بزرگ‌تر فاصله را دست‌کاری می‌کنند

بعد از Z-Score، همه ویژگی‌ها تأثیر یکسان دارند